In [1]:
import numpy as np

In [4]:
#1
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
#2
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [17]:
#3
arr_2d = np.array(([0,1,2],[3,4,5],[6,7,8]))
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
#4
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
#5
arr_2d = np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]))
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [48]:
#6
arr_2d[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [52]:
#7
arr_2d[3,4]

20

In [53]:
#8
arr_2d.max()

25

In [54]:
arr_2d.min()

1

In [55]:
arr_2d.argmax()

24

In [56]:
arr_2d.argmin()

0

In [3]:
#9
nilai = np.arange(1,25)
nilai

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [7]:
#10
nilai[10:20]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])